### ISSUE TITLE
Request: Build Filename Without Version Number

### ISSUE THREAD

**Issue by bigtimebuddy** [CreateJS/TweenJS#74]
Would it be possible to please remove the version number from the concatenated library file names (e.g., "tweenjs-0.6.1.min.js" becomes "tweenjs.min.js")? This is not particularly helpful and creates manual annoyances when upgrading to newer versions of the library. Bower is the preferred method for managing dependency versions and feel that file name versioning is unnecessary and redundant. What's the rationale for this choice?

**Comment by lannymcnie** [comment]
This has been requested a few times, but we are unlikely to make the change. The libs in GitHub are discrete versions, and any updating that you do should be explicit.

**Comment by gskinner** [comment]
We may evaluate this for 1.0.

**Comment by pvnr0082t** [comment]
Hi @lannymcnie @gskinner ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). This lib had already been hosted in cdnjs.
But it's hard to automatically update for this lib because of the naming scheme. So I prefer not to name files with the version number. Thanks.

https://github.com/cdnjs/cdnjs/pull/9157
https://github.com/cdnjs/cdnjs/issues/9146
https://github.com/cdnjs/cdnjs/issues/8766

**Comment by lannymcnie** [comment]
We have moved to builds without version numbers as-of 1.0.
Cheers!
